font_family JetBrainsMono Nerd Font Mono
background_opacity 1
background_blur 1
window_padding_width 16

# COLORS
background #121214
foreground #929292
selection_foreground #929292
selection_background #26282b
color1 #e85151
color2 #69bd63
color3 #e4bb70
color4 #7280b9
color5 #ff9ad7
color6 #64a4ac
color9 #e85151
color10 #69bd63
color11 #e4bb70
cursor #26282b
cursor_trail_color #26282b

cursor_beam_thickness 7
# cursor_blink_interval 0.5 ease-out
cursor_trail 0
cursor_trail_decay 0.2 0.8
cursor_trail_start_threshold 1
scrollbar_width 0.8
scrollbar_radius 0.4
scrollbar_gap 0.4
scrollbar_handle_opacity 1.0
scrollbar_handle_color #292932
tab_bar_edge top
# tab_bar_min_tabs 1
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground #ffffff
active_tab_background #72c2c2
inactive_tab_foreground #ffffff
inactive_tab_background #ff9ad7
enabled_layouts stack
confirm_os_window_close 0
