font_family JetBrainsMono Nerd Font Mono
background_opacity 0.8
background_blur 1
background #292932
foreground #b8b1a9
selection_foreground #292932
selection_background #b8b1a9
window_padding_width 16

color2 #69bd63
color4 #7280b9
color5 #ff9ad7
color6 #72c2c2
color10 #6fe77f
color11 #dbb37e
cursor #b8b1a9

cursor_beam_thickness 7
# cursor_blink_interval 0.5 ease-out
cursor_trail 0
cursor_trail_decay 0.2 0.8
cursor_trail_start_threshold 1
cursor_trail_color #b8b1a9

scrollbar_width 0.8
scrollbar_radius 0.4
scrollbar_gap 0.4
scrollbar_handle_opacity 1.0
scrollbar_handle_color #b8b1a9

tab_bar_edge top
# tab_bar_min_tabs 1
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground #ffffff
active_tab_background #72c2c2
inactive_tab_foreground #ffffff
inactive_tab_background #ff9ad7

enabled_layouts stack
confirm_os_window_close 0

