# CURRENT_THEME

# Text
#929292

# Border
#38383e

# Main BG - Firefox, VSC
#1a1a1c

# Secondary BG
#26282b
 

# Accents
color2 #69bd63
color4 #7280b9
color5 #ff9ad7
color6 #72c2c2
color10 #6fe77f
color11 #dbb37e
cursor #b8b1a9
